services:
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - ingestion-net
    restart: unless-stopped

networks:
  ingestion-net:
    external: true