global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: worker-postgres
    metrics_path: /metrics
    static_configs:
      - targets: ["worker-postgres:8000"]

  - job_name: ingestor-pcap
    metrics_path: /metrics
    static_configs:
      - targets: ["ingestor-pcap:8000"]
      - targets: ["host.docker.internal:8002"]
        labels:
          source: "live-host"